### PR TITLE
[#167] Removal of unnecessary catch blocks

### LINKED ISSUE #167: Unnecessary catch block in MainApp and Exceptions in Interfaces
In MainApp.java,

```java
        try {
            addressBookOptional = storage.readAddressBook();
            if (!addressBookOptional.isPresent()) {
                logger.info("Data file not found. Will be starting with a sample AddressBook");
            }
            initialData = addressBookOptional.orElseGet(SampleDataUtil::getSampleAddressBook);
        } catch (DataConversionException e) {
            logger.warning("Data file not in the correct format. Will be starting with an empty AddressBook");
            initialData = new AddressBook();
        } catch (IOException e) {
            logger.warning("Problem while reading from the file. Will be starting with an empty AddressBook");
            initialData = new AddressBook();
        }
```
```java
        try {
            Optional<UserPrefs> prefsOptional = storage.readUserPrefs();
            initializedPrefs = prefsOptional.orElse(new UserPrefs());
        } catch (DataConversionException e) {
            logger.warning("UserPrefs file at " + prefsFilePath + " is not in the correct format. "
                    + "Using default user prefs");
            initializedPrefs = new UserPrefs();
        } catch (IOException e) {
            logger.warning("Problem while reading from the file. Will be starting with an empty AddressBook");
            initializedPrefs = new UserPrefs();
        }
```

The IOException was due to `readUserPrefs()` and `readAddressBook()` possibly throwing `IOException` suggested by their respective interface files.

However, in the actual implementation of the methods, the `IOException` is actually already handled within the functions itself so this means that `IOException` is actually never thrown. Thus, I believe it is safe to remove the catch statement for `IOException` as well as in the interface. 

e.g. 
### readUserPref()
In StorageManager.java
```java
    @Override
    public Optional<UserPrefs> readUserPrefs() throws DataConversionException, IOException {
        return userPrefsStorage.readUserPrefs();
    }
```
In JsonUserPrefStorage.java
```java

    @Override
    public Optional<UserPrefs> readUserPrefs() throws DataConversionException {
        return readUserPrefs(filePath);
    }

    /**
     * Similar to {@link #readUserPrefs()}
     * @param prefsFilePath location of the data. Cannot be null.
     * @throws DataConversionException if the file format is not as expected.
     */
    public Optional<UserPrefs> readUserPrefs(Path prefsFilePath) throws DataConversionException {
        return JsonUtil.readJsonFile(prefsFilePath, UserPrefs.class);
    }
```
In JsonUtil.java
```java
    public static <T> Optional<T> readJsonFile(
            Path filePath, Class<T> classOfObjectToDeserialize) throws DataConversionException {
        requireNonNull(filePath);

        if (!Files.exists(filePath)) {
            logger.info("Json file " + filePath + " not found");
            return Optional.empty();
        }

        T jsonFile;

        try {
            jsonFile = deserializeObjectFromJsonFile(filePath, classOfObjectToDeserialize);
        } catch (IOException e) {
            logger.warning("Error reading from jsonFile file " + filePath + ": " + e);
            throw new DataConversionException(e);
        }

        return Optional.of(jsonFile);
    }
```
---
### readAddressBook()
in StorageManager.java
```java
@Override
    public Optional<ReadOnlyAddressBook> readAddressBook() throws DataConversionException, IOException {
        return readAddressBook(addressBookStorage.getAddressBookFilePath());
    }

    @Override
    public Optional<ReadOnlyAddressBook> readAddressBook(Path filePath) throws DataConversionException, IOException {
        logger.fine("Attempting to read data from file: " + filePath);
        return addressBookStorage.readAddressBook(filePath);
    }
```
In JsonAddressBookStorage.java
```java
    @Override
    public Optional<ReadOnlyAddressBook> readAddressBook() throws DataConversionException {
        return readAddressBook(filePath);
    }

    /**
     * Similar to {@link #readAddressBook()}.
     *
     * @param filePath location of the data. Cannot be null.
     * @throws DataConversionException if the file is not in the correct format.
     */
    public Optional<ReadOnlyAddressBook> readAddressBook(Path filePath) throws DataConversionException {
        requireNonNull(filePath);

        Optional<JsonSerializableAddressBook> jsonAddressBook = JsonUtil.readJsonFile(
                filePath, JsonSerializableAddressBook.class);
        if (!jsonAddressBook.isPresent()) {
            return Optional.empty();
        }

        try {
            return Optional.of(jsonAddressBook.get().toModelType());
        } catch (IllegalValueException ive) {
            logger.info("Illegal values found in " + filePath + ": " + ive.getMessage());
            throw new DataConversionException(ive);
        }
    }
```

We can see that none of the classes that implemented those interface actually throws `IOExceptions`

### PR DESCRIPTION
**Pull request by Eclipse-Dominator**
Fixes #167 

Alternative approach: #186 (Where functionality of the catch blocks is restored)

---

Following issue #167, all IOExceptions are already being handled within `JsonUtil#readJsonFile()`, therefore additional catch blocks as well as throwing of IOExceptions are no longer needed.

This PR moves handling of conversion errors as well as regular IOExceptions to within `JsonUtil#readJsonFile()`. As a result of this change, it is no longer appropriate to call the exception thrown `DataConversionException`. 

Thus, the above-mentioned exception will be renamed to `DataLoadingException`. Affected interfaces and code caused by this change will then be updated.

### CODE REVIEW

**Review by damithc — COMMENTED** [review]
Quick feedback: The renaming of the exception class deserves its own commit?

File: src/main/java/seedu/address/commons/exceptions/DataConversionException.java [hunk 1]
```diff
@@ -1,7 +1,7 @@
 package seedu.address.commons.exceptions;
 
 /**
- * Represents an error during conversion of data from one format to another
+ * Represents an error during loading of files from the file system.
```
Comment (damithc) [inline src/main/java/seedu/address/commons/exceptions/DataConversionException.java]: I think this belongs in the other commit, together with the name change.

Comment (damithc) [reply src/main/java/seedu/address/commons/exceptions/DataConversionException.java]: Strictly speaking, the correct order is to tweak the exception first, and then remove the catch blocks. The latter is more justifiable after the exception has been tweaked.

File: src/main/java/seedu/address/commons/util/JsonUtil.java [hunk 2]
```diff
@@ -49,14 +49,16 @@ static <T> T deserializeObjectFromJsonFile(Path jsonFile, Class<T> classOfObject
     }
 
     /**
-     * Returns the Json object from the given file or {@code Optional.empty()} object if the file is not found.
-     * If any values are missing from the file, default values will be used, as long as the file is a valid json file.
+     * Returns the Json object from the given file or {@code Optional.empty()} object if the file is
```
Comment (damithc) [inline src/main/java/seedu/address/commons/util/JsonUtil.java]: Not strictly related to this PR but as long as we are touching these lines, perhaps use `JSON` or `json` instead of `Json`?

File: src/main/java/seedu/address/commons/util/JsonUtil.java [hunk 3]
```diff
@@ -49,14 +49,16 @@ static <T> T deserializeObjectFromJsonFile(Path jsonFile, Class<T> classOfObject
...
+     * not found. If any values are missing from the file, default values will be used, as long as
+     * the file is a valid json file.
+     *
      * @param filePath cannot be null.
      * @param classOfObjectToDeserialize Json file has to correspond to the structure in the class given here.
-     * @throws DataConversionException if the file format is not as expected.
+     * @throws DataConversionException if the loading of file failed
```
Comment (damithc) [inline src/main/java/seedu/address/commons/util/JsonUtil.java]: Not sure if `loading of the file` will be understood as both 'reading the file content and parsing the content'. Perhaps use `loading of JSON data from the file`?

File: src/main/java/seedu/address/storage/JsonUserPrefsStorage.java [hunk 4]
```diff
@@ -32,8 +32,9 @@ public Optional<UserPrefs> readUserPrefs() throws DataConversionException {
 
     /**
      * Similar to {@link #readUserPrefs()}
+     *
      * @param prefsFilePath location of the data. Cannot be null.
-     * @throws DataConversionException if the file format is not as expected.
+     * @throws DataConversionException if the loading of the preference file fails.
```
Comment (damithc) [inline src/main/java/seedu/address/storage/JsonUserPrefsStorage.java]: This is phrasing is slightly different from the one used in `readAddressBook`. Don't vary things unless there is a good reason.

File: src/main/java/seedu/address/storage/JsonAddressBookStorage.java [hunk 5]
```diff
@@ -40,7 +40,7 @@ public Optional<ReadOnlyAddressBook> readAddressBook() throws DataConversionExce
      * Similar to {@link #readAddressBook()}.
      *
      * @param filePath location of the data. Cannot be null.
-     * @throws DataConversionException if the file is not in the correct format.
+     * @throws DataConversionException if the loading of the data fails.
```
Comment (damithc) [inline src/main/java/seedu/address/storage/JsonAddressBookStorage.java]: fails -> failed?

File: src/test/java/seedu/address/commons/util/ConfigUtilTest.java [hunk 6]
```diff
@@ -68,7 +68,8 @@ private Config getTypicalConfig() {
         return config;
     }
 
-    private Optional<Config> read(String configFileInTestDataFolder) throws DataConversionException {
+    private Optional<Config> read(String configFileInTestDataFolder)
+            throws DataConversionException {
```
Comment (damithc) [inline src/test/java/seedu/address/commons/util/ConfigUtilTest.java]: This change is not needed?

File: src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java [hunk 7]
```diff
@@ -47,17 +47,20 @@ public void read_missingFile_emptyResult() throws Exception {
 
     @Test
     public void read_notJsonFormat_exceptionThrown() {
-        assertThrows(DataConversionException.class, () -> readAddressBook("notJsonFormatAddressBook.json"));
+        assertThrows(DataConversionException.class,
+                () -> readAddressBook("notJsonFormatAddressBook.json"));
```
Comment (damithc) [inline src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java]: Revert unrelated changes.

**Review by damithc — CHANGES_REQUESTED** [review]
Some suggestions added.

File: src/main/java/seedu/address/commons/util/JsonUtil.java (hunk 3 above)
Comment (Eclipse-Dominator) [reply src/main/java/seedu/address/commons/util/JsonUtil.java]: For this version of PR, the handling of trying to read file content and parsing the content is both handled within `JsonUtil` so in a sense the new renamed exception represents both 'reading the file content and parsing the content'.

File: src/main/java/seedu/address/MainApp.java [hunk 8]
```diff
@@ -10,7 +10,7 @@
 import seedu.address.commons.core.Config;
```
Comment (damithc) [inline src/main/java/seedu/address/MainApp.java:10]: Commit message can be shorter:
```
Rename DataConversoinException -> ConfigLoadingException

DataConversoinException is thrown to indicate any problem
encountered while reading a JSON config file, not just problems
specific to data conversion.

Let's rename it as ConfigLoadingException to make the name
more representative of its purpose.
```

File: src/main/java/seedu/address/commons/exceptions/ConfigLoadingException.java [hunk 9]
```diff
@@ -3,8 +3,8 @@
 /**
  * Represents an error during conversion of data from one format to another
```
Comment (damithc) [inline src/main/java/seedu/address/commons/exceptions/ConfigLoadingException.java]: `Represents an error during loading of data from a config file.`

**Review by damithc — CHANGES_REQUESTED** [review]
The first commit should be just the renaming. It is a mechanical change and requires minimal review. The only other thing that can be go into that commit is the tweaking of the javadoc comment of that class so that the comment matches the new class name.
Once that is out of the way, the next commit can focus on behavioral tweaks.

File: src/main/java/seedu/address/storage/StorageManager.java [hunk 10]
```diff
@@ -54,12 +54,12 @@ public Path getAddressBookFilePath() {
     }
 
     @Override
-    public Optional<ReadOnlyAddressBook> readAddressBook() throws DataConversionException, IOException {
+    public Optional<ReadOnlyAddressBook> readAddressBook() throws ConfigLoadingException, IOException {
```
Comment (damithc) [inline src/main/java/seedu/address/storage/StorageManager.java]: Wait, this doesn't look right. I think we have to name it `DataLoadingException` instead.

**Review by damithc — CHANGES_REQUESTED** [review]
Mostly OK. I suggest the following:
* Commit 1: Remove everything else except those strictly related to renaming the exception. It should look almost like a mechanical find-and-replace refactoring. 
* Commit 2: commit message: No need to mention 'In the previous commit'. The previous commit speaks for itself. Here, mention that IOException is unnecessary and is removed, and logs/docs are adjusted accordingly.

File: src/main/java/seedu/address/MainApp.java [hunk 11]
```diff
@@ -125,7 +121,7 @@ protected Config initConfig(Path configFilePath) {
             }
             initializedConfig = configOptional.orElse(new Config());
         } catch (DataLoadingException e) {
-            logger.warning("Config file at " + configFilePathUsed + " is not in the correct format."
+            logger.warning("Config file at " + configFilePathUsed + " could not be read."
```
Comment (damithc) [inline src/main/java/seedu/address/MainApp.java]: Should this be `could not be loaded.` instead?

File: src/main/java/seedu/address/storage/AddressBookStorage.java [hunk 12]
```diff
@@ -19,16 +19,16 @@ public interface AddressBookStorage {
 
     /**
      * Returns AddressBook data as a {@link ReadOnlyAddressBook}.
-     *   Returns {@code Optional.empty()} if storage file is not found.
+     * Returns {@code Optional.empty()} if storage file is not found.
+     *
      * @throws DataLoadingException if the data in storage is not in the expected format.
```
Comment (damithc) [inline src/main/java/seedu/address/storage/AddressBookStorage.java]: Doesn't this need updating as well?

File: src/main/java/seedu/address/MainApp.java [hunk 13]
```diff
@@ -84,13 +84,9 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
             }
```
Comment (damithc) [inline src/main/java/seedu/address/MainApp.java:84]: Suggested alternative commit message:
```
JsonUtil#readJsonFile() method throws a DataLoadingException when it
detects an IOException.  However, some client code of that method are 
written as if it throws an IOException.

Let's,
1. remove 'throws IOExceptions' clause from the relevant client methods
   in Storage, AddressBookStorage, and UserPrefsStorage.
2. remove corresponding catch blocks.
3. tweak relevant javadocs and log message to match.
```

**Review by damithc — COMMENTED** [review]
Commit 1: Clean and easy to review. Nice!
Commit 2: Added a few cosmetic suggestions.

**Comment by damithc** [comment]
@Eclipse-Dominator Can you update the PR description to match the current state of the PR? After that, I'll ask others for reviews.

File: src/main/java/seedu/address/storage/AddressBookStorage.java (hunk 12 above)
Comment (Eclipse-Dominator) [reply src/main/java/seedu/address/storage/AddressBookStorage.java]: I missed out this when doing the rebasing to shift the documentation change to the 2nd commit.

**Comment by damithc** [comment]
@se-edu/tech-team-level1 for your review ...

**Review by SPWwj — APPROVED** [review]
LGTM! Now, the MainApp.java has become more streamlined, and the exceptions are more specific. Excellent work!

**Comment by damithc** [comment]
Thanks @Eclipse-Dominator for the fix, and @SPWwj for the review.
